version: '3'
services:
#    db:
#        image: mariadb:latest
#        volumes:
#            - moodle_data:/var/lib/mysql
#        restart: always
#        environment:
#            MYSQL_ROOT_PASSWORD: 
#            MYSQL_DATABASE: moodle
#            MYSQL_USER: moodle
#            MYSQL_PASSWORD: m00dle
#        networks:
#            - moodle


   db:
      image: mysql:5.7
      volumes:
           - moodle_data:/var/lib/mysql
      restart: always 
      environment:
              MYSQL_ROOT_PASSWORD: farman17
              MYSQL_USER: admin
              MYSQL_PASSWORD: farman17
              MYSQL_DATABASE: babiguling
      networks:
           - moodle


        
   app:
       depends_on: 
           - db
       image: prasta/moodle:latest
       ports:
           - "3003:80"
       restart: always
       networks:
           - moodle


volumes:
    moodle_data:        


networks:
    moodle:
